import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainLayout from "@admin/components/layout/main-layout";
import SessionLocalProvider from "@admin/store/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SessionLocalProvider>
          <MainLayout>{children}</MainLayout>
        </SessionLocalProvider>
      </body>
    </html>
  );
}
