// "use client";
import "./globals.css";
import React, { StrictMode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainLayout from "@admin/components/layout/main-layout";
import SessionLocalProvider from "@admin/store/session-provider";
import { NextUIProviders } from "@admin/components/layout/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StrictMode>
          <NextUIProviders>
            <SessionLocalProvider>
              <MainLayout>{children}</MainLayout>
            </SessionLocalProvider>
          </NextUIProviders>
        </StrictMode>
      </body>
    </html>
  );
}
